### PR TITLE
Fixed the handling of the exception thrown by registration in case an email is already used

### LINKED ISSUE #19: Bad logic with the Firebase API
Misuse of this function. In the call stack, it ends up invoking `createUserWithEmailAndPassword`, which throws an exception if the **email is already** in use [1]. It is necessary to handle this with a `catch`. Furthermore, the error message in the snackbar (which is never reached) is incorrect [2]. Password validation is performed during form completion. On submit, you can verify if the email is invalid.

[1] https://github.com/benedettoscala/CiviConnect/blob/f0ee58333c6f57033192f98907aa640554a9a0db/src/lib/user_management/registrazione_utente_gui.dart#L321

[2] https://github.com/benedettoscala/CiviConnect/blob/f0ee58333c6f57033192f98907aa640554a9a0db/src/lib/user_management/registrazione_utente_gui.dart#L339

@Marco-Brescia fix please.

### PR DESCRIPTION
**Pull request by GiuseppeGambardella**
### - In case of error, the GUI notifies the user that the email is already in use.

### CODE REVIEW

File: src/lib/user_management/registrazione_utente_gui.dart [hunk 1]
```diff
@@ -317,17 +316,17 @@ class _RegistrazioneUtenteGuiState extends State<RegistrazioneUtenteGui> {
     // Sends the email and password to the controller.
     UserManagementController controller =
         UserManagementController(redirectPage: const HomePage());
-
-    validUser = await controller.register(context,
```
Comment (Peppe289) [inline src/lib/user_management/registrazione_utente_gui.dart:321]: Why did you remove the if statement with the return value?

Comment (Peppe289) [reply src/lib/user_management/registrazione_utente_gui.dart:321]: Please check how the login is implemented.

Comment (GiuseppeGambardella) [reply src/lib/user_management/registrazione_utente_gui.dart:321]: The statement was removed because now if the registration has an error, it generates an exception that is caught in the GUI, implicitly meaning that the user is not valid

**Review by benedettoscala — APPROVED** [review]

File: src/lib/user_management/registrazione_utente_gui.dart (hunk 1 above)
Comment (Peppe289) [reply src/lib/user_management/registrazione_utente_gui.dart:321]: > The statement was removed because now if the registration has an error, it generates an exception that is caught in the GUI, implicitly meaning that the user is not valid

ok, LGTM! thx

**Review by Luigi11162 — APPROVED** [review]
LGTM! Approved
